# This is a basic workflow that is manually triggered

name: Build and Deploy using Docker

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install heroku tool chain
      run: npm install -g heroku
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: maven_project_with_dockerfile
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to Heroku registry
      uses: docker/login-action@v1 
      with:
        registry: registry.heroku.com  
        username: ${{ secrets.HEROKU_EMAIL  }}
        password: ${{ secrets.HEROKU_API_KEY }}
    - name: Login to Heroku Container
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login 
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: maven_project_with_dockerfile
        push: true
        tags: |
          himanshumps/vertx_demo:latest
          registry.heroku.com/vertxdemo23170/web
    - name: Heroku release the pushed image
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release web -a vertxdemo23170
